[package]
name = "gtfo-like-game"
version = "0.1.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
description = "A GTFO-like cooperative survival horror game built with Bevy and Avian"

[lib]
name = "gtfo_like_game"
path = "src/lib.rs"

[[bin]]
name = "full"
path = "src/main.rs"

[dependencies]
# Core Bevy engine
bevy = { version = "0.16", features = [
    "dynamic_linking",
    "bevy_gltf",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_asset",
    "bevy_scene",
    "bevy_animation",
    "bevy_ui",
    "bevy_text",
    "png",
    "hdr",
    "ktx2",
    "zstd",
    "tonemapping_luts",
    "multi_threaded",
    "bevy_debug_stepping",
] }

# Avian physics engine (updated for Bevy 0.16 compatibility)
avian3d = "0.3.1"

# Networking for multiplayer (compatible with Bevy 0.16) - temporarily disabled
bevy_renet = "1.0"
renet = "1.0"

# Audio (compatible with Bevy 0.16)
bevy_kira_audio = { version = "0.23.0", features = ["mp3"] }

# EGUI for debug UI
bevy_egui = "0.35.1"
bevy-inspector-egui = "0.32.0"

# Random number generation
rand = "0.9.2"

# Procedural generation
noise = "0.9.0"
bracket-random = "0.8"

# Serialization for save/load and networking
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.1"

# Input handling (compatible with Bevy 0.16)
leafwing-input-manager = "0.17.1"

# Utilities
anyhow = "1.0"

# Fast compilation optimizations for development
[profile.dev]
# Enable only a small amount of optimization in the dev profile
opt-level = 1
# Enable incremental compilation for faster rebuilds
incremental = true

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Optional: Also enable high optimizations for some dependencies individually:
[profile.dev.package.bevy]
opt-level = 3

[profile.dev.package.avian3d]
opt-level = 3

# Release optimizations
[profile.release]
# Enable link-time optimization for smaller binary size
lto = true
# Optimize for size in release
opt-level = "s"
# Strip debug symbols in release
strip = true
